version: '3'
services:
  fhir-server:
    image: "hapiproject/hapi:latest-tomcat"
    ports:
      -   "8090:8080"
    environment:
      spring.datasource.url: "jdbc:postgresql://fhir-db:5432/hapi_r4"
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      hapi.fhir.subsrciption.resthook_enabled: "true"
      hapi.fhir.subsrciption.websocket_enabled: "true"
      hapi.fhir.client_id_strategy: ANY

  fhir-db:
      image: postgres
      volumes:
        - fhir-db-data:/var/lib/postgresql/data
      environment:
         POSTGRES_PASSWORD: admin
         POSTGRES_USERNAME: admin
         POSTGRES_DB: hapi_r4

  ehrbase:
      image: ehrbase/ehrbase:next
      environment:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/ehrbase"
          SPRING_DATASOURCE_USERNAME: ehrbase
          SPRING_DATASOURCE_PASSWORD: ehrbase
          SERVER_AQLCONFIG_USEJQUERY: "false"
      restart: on-failure
      depends_on:
          - db
      ports:
          - "8081:8080"

  db:
      image: postgres
      volumes:
          - db-data:/var/lib/postgresql/data
      environment:
          POSTGRES_USER: ehrbase
          POSTGRES_PASSWORD: ehrbase
          POSTGRES_DB: ehrbase

volumes:
   fhir-db-data:
   db-data:
