version: '3'
services:
  fhir-server:
    image: "hapiproject/hapi:latest-tomcat"
    ports:
      -   "8090:8080"
    environment:
      spring.datasource.url: "jdbc:postgresql://fhirdb:5432/hapi_r4"
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      hapi.fhir.subsrciption.resthook_enabled: "true"
      hapi.fhir.subsrciption.websocket_enabled: "true"
      12hapi.fhir.client_id_strategy: ANY

  fhirdb:
    image: postgres:latest
    volumes:
      - fhirdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USERNAME: admin
      POSTGRES_DB: hapi_r4
    ports:
      - "5431:5432"

  ehrbase:
    image: ehrbase/ehrbase@sha256:74c97d56ed00b1a89be18153f30ea3766fec67a876327fb8e5b623d535e386ce
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ehrdb:5432/ehrbase"
      SPRING_DATASOURCE_USERNAME: ehrbase
      SPRING_DATASOURCE_PASSWORD: ehrbase
      SERVER_AQLCONFIG_USEJSQUERY: "false"
      SERVER_NODENAME: "localhost"
      WEB_CORS_ALLOWEDORIGINPATTERNS: "*"
      WEB_CORS_ALLOWEDMETHODS: "GET,PUT,DELETE,POST,OPTIONS"
      WEB_CORS_ALLOWCREDENTIALS: "true"
    depends_on:
      - ehrdb
    ports:
      - "8080:8080"
    restart: on-failure

  ehrdb:
    image: postgres:latest
    volumes:
      - ehrdb-data:/var/lib/postgresql/data
      - ./cloud-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  ehrdb-data:
  fhirdb-data:
