version: "3.3"
services:
  nats:
    image: nats:${NATS_TAG}
    ports:
      - "4222:4222"
  db:
    image: postgres:13.4
    command:
      - -c
      - max_replication_slots=10
      - -c
      - wal_level=logical
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  ehrbase:
    image: ehrbase/ehrbase@sha256:74c97d56ed00b1a89be18153f30ea3766fec67a876327fb8e5b623d535e386ce
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ehrdb:5432/ehrbase"
      SPRING_DATASOURCE_USERNAME: ehrbase
      SPRING_DATASOURCE_PASSWORD: ehrbase
      SERVER_AQLCONFIG_USEJSQUERY: "false"
      SERVER_NODENAME: "localhost"
      WEB_CORS_ALLOWEDORIGINPATTERNS: "*"
      WEB_CORS_ALLOWEDMETHODS: "GET,PUT,DELETE,POST,OPTIONS"
      WEB_CORS_ALLOWCREDENTIALS: "true"
    depends_on:
      - ehrdb
    ports:
      - "8080:8080"
    restart: on-failure

  ehrdb:
    image: postgres:latest
    volumes:
      - ehrdb-data:/var/lib/postgresql/data
      - ./cloud-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  db-data:
  caddy_data:
  caddy_config:
