version: '3'
services:
  fhir-server:
    image: "hapiproject/hapi:latest-tomcat"
    ports:
      -   "8090:8080"
    environment:
      spring.datasource.url: "jdbc:postgresql://fhir-db:5433/hapi_r4"
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      hapi.fhir.subsrciption.resthook_enabled: "true"
      hapi.fhir.subsrciption.websocket_enabled: "true"
      hapi.fhir.client_id_strategy: ANY
    depends_on:
      - fhir-db

  fhir-db:
      image:  yugabytedb/yugabyte:latest
      #image: postgres:latest
      command: |
       bash -c "
       # create database and user as soon as database is up
       until [ -z "POSTGRES_USER" ] || PGPASSWORD=admin bin/ysqlsh -v ON_ERROR_STOP=1 \\
        -c \"create database $${POSTGRES_DB:-$${POSTGRES_USER}} \" \\
        -c \"create user $${POSTGRES_USER} password '$${POSTGRES_PASSWORD}' \" \\
        2>/dev/null
        do
         echo \"Waiting for YugabyteDB to be up for creating user $${POSTGRES_USER}.\" ; sleep 5
        done &
       # start YugabyteDB
       bin/yugabyted start --listen 0.0.0.0 --daemon=false --tserver_flags='ysql_enable_auth=true'
       "
      volumes:
        - fhir-db-data:/var/lib/postgresql/data
      environment:
         POSTGRES_PASSWORD: admin
         POSTGRES_USERNAME: admin
         POSTGRES_DB: hapi_r4
      ports:
        - "15432:5433"

  ehrbase:
      image: ehrbase/ehrbase:next
      environment:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5433/ehrbase"
          SPRING_DATASOURCE_USERNAME: ehrbase
          SPRING_DATASOURCE_PASSWORD: ehrbase
          SERVER_AQLCONFIG_USEJQUERY: "false"
      restart: on-failure
      depends_on:
          - db
      ports:
          - "8080:8080"

  db:
      image: yugabytedb/yugabyte:latest
      #image: postgres:latest
      command: |
       bash -c "
       # create database and user as soon as database is up
       until [ -z "POSTGRES_USER" ] || PGPASSWORD=ehrbase bin/ysqlsh -v ON_ERROR_STOP=1 \\
        -c \"create database $${POSTGRES_DB:-$${POSTGRES_USER}} \" \\
        -c \"create user $${POSTGRES_USER} password '$${POSTGRES_PASSWORD}' \" \\
        2>/dev/null
        do
         echo \"Waiting for YugabyteDB to be up for creating user $${POSTGRES_USER}.\" ; sleep 5
        done &
       # start YugabyteDB
       bin/yugabyted start --listen 0.0.0.0 --daemon=false --tserver_flags='ysql_enable_auth=true'
       "
      volumes:
          - db-data:/var/lib/postgresql/data
      environment:
          POSTGRES_USER: ehrbase
          POSTGRES_PASSWORD: ehrbase
          POSTGRES_DB: ehrbase
      ports:
        - "1543:5433"
        - "7000:7000"


#  yugabytedb:
#    image: docker.io/yugabytedb/yugabyte:latest
#    command: |
#     bash -c "
#     # create database and user as soon as database is up
#     until [ -z "POSTGRES_USER" ] || PGPASSWORD=ehrbase bin/ysqlsh -v ON_ERROR_STOP=1 \\
#      -c \"create database $${POSTGRES_DB:-$${POSTGRES_USER}} \" \\
#      -c \"create user $${POSTGRES_USER} password '$${POSTGRES_PASSWORD}' \" \\
#      2>/dev/null
#      do
#       echo \"Waiting for YugabyteDB to be up for creating user $${POSTGRES_USER}.\" ; sleep 5
#      done &
#     # start YugabyteDB
#     bin/yugabyted start --listen 0.0.0.0 --daemon=false --tserver_flags='ysql_enable_auth=true'
#     "
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DB=hapi_r4
#    ports:
#      - 25433:5433
#      - 27000:7000
#
#  waityugabyte:
#    image: postgres:13-alpine
#    links:
#      - yugabytedb
#    depends_on:
#      - yugabytedb
#    entrypoint:
#      - bash
#      - -c
#      - 'until PGPASSWORD=admin /usr/local/bin/psql postgres://ehrbase@yugabytedb:5433/hapi_r4 -c "SELECT 1"; do sleep 5; done'
#
volumes:
  fhir-db-data:
  #yugabytedb:
  db-data:
  #waityugabyte:
